-- Seed all countries of the world as root localities
-- These serve as the top-level parents in the locality hierarchy

INSERT INTO public.localities (name, kind, parent_id) VALUES
  ('Afghanistan', 'country', NULL),
  ('Albania', 'country', NULL),
  ('Algeria', 'country', NULL),
  ('Andorra', 'country', NULL),
  ('Angola', 'country', NULL),
  ('Antigua and Barbuda', 'country', NULL),
  ('Argentina', 'country', NULL),
  ('Armenia', 'country', NULL),
  ('Australia', 'country', NULL),
  ('Austria', 'country', NULL),
  ('Azerbaijan', 'country', NULL),
  ('Bahamas', 'country', NULL),
  ('Bahrain', 'country', NULL),
  ('Bangladesh', 'country', NULL),
  ('Barbados', 'country', NULL),
  ('Belarus', 'country', NULL),
  ('Belgium', 'country', NULL),
  ('Belize', 'country', NULL),
  ('Benin', 'country', NULL),
  ('Bhutan', 'country', NULL),
  ('Bolivia', 'country', NULL),
  ('Bosnia and Herzegovina', 'country', NULL),
  ('Botswana', 'country', NULL),
  ('Brazil', 'country', NULL),
  ('Brunei', 'country', NULL),
  ('Bulgaria', 'country', NULL),
  ('Burkina Faso', 'country', NULL),
  ('Burundi', 'country', NULL),
  ('Cabo Verde', 'country', NULL),
  ('Cambodia', 'country', NULL),
  ('Cameroon', 'country', NULL),
  ('Canada', 'country', NULL),
  ('Central African Republic', 'country', NULL),
  ('Chad', 'country', NULL),
  ('Chile', 'country', NULL),
  ('China', 'country', NULL),
  ('Colombia', 'country', NULL),
  ('Comoros', 'country', NULL),
  ('Congo (Democratic Republic)', 'country', NULL),
  ('Congo (Republic)', 'country', NULL),
  ('Costa Rica', 'country', NULL),
  ('Croatia', 'country', NULL),
  ('Cuba', 'country', NULL),
  ('Cyprus', 'country', NULL),
  ('Czech Republic', 'country', NULL),
  ('Denmark', 'country', NULL),
  ('Djibouti', 'country', NULL),
  ('Dominica', 'country', NULL),
  ('Dominican Republic', 'country', NULL),
  ('Ecuador', 'country', NULL),
  ('Egypt', 'country', NULL),
  ('El Salvador', 'country', NULL),
  ('Equatorial Guinea', 'country', NULL),
  ('Eritrea', 'country', NULL),
  ('Estonia', 'country', NULL),
  ('Eswatini', 'country', NULL),
  ('Ethiopia', 'country', NULL),
  ('Fiji', 'country', NULL),
  ('Finland', 'country', NULL),
  ('France', 'country', NULL),
  ('Gabon', 'country', NULL),
  ('Gambia', 'country', NULL),
  ('Georgia', 'country', NULL),
  ('Germany', 'country', NULL),
  ('Ghana', 'country', NULL),
  ('Greece', 'country', NULL),
  ('Grenada', 'country', NULL),
  ('Guatemala', 'country', NULL),
  ('Guinea', 'country', NULL),
  ('Guinea-Bissau', 'country', NULL),
  ('Guyana', 'country', NULL),
  ('Haiti', 'country', NULL),
  ('Honduras', 'country', NULL),
  ('Hungary', 'country', NULL),
  ('Iceland', 'country', NULL),
  ('India', 'country', NULL),
  ('Indonesia', 'country', NULL),
  ('Iran', 'country', NULL),
  ('Iraq', 'country', NULL),
  ('Ireland', 'country', NULL),
  ('Israel', 'country', NULL),
  ('Italy', 'country', NULL),
  ('Ivory Coast', 'country', NULL),
  ('Jamaica', 'country', NULL),
  ('Japan', 'country', NULL),
  ('Jordan', 'country', NULL),
  ('Kazakhstan', 'country', NULL),
  ('Kenya', 'country', NULL),
  ('Kiribati', 'country', NULL),
  ('Kosovo', 'country', NULL),
  ('Kuwait', 'country', NULL),
  ('Kyrgyzstan', 'country', NULL),
  ('Laos', 'country', NULL),
  ('Latvia', 'country', NULL),
  ('Lebanon', 'country', NULL),
  ('Lesotho', 'country', NULL),
  ('Liberia', 'country', NULL),
  ('Libya', 'country', NULL),
  ('Liechtenstein', 'country', NULL),
  ('Lithuania', 'country', NULL),
  ('Luxembourg', 'country', NULL),
  ('Madagascar', 'country', NULL),
  ('Malawi', 'country', NULL),
  ('Malaysia', 'country', NULL),
  ('Maldives', 'country', NULL),
  ('Mali', 'country', NULL),
  ('Malta', 'country', NULL),
  ('Marshall Islands', 'country', NULL),
  ('Mauritania', 'country', NULL),
  ('Mauritius', 'country', NULL),
  ('Mexico', 'country', NULL),
  ('Micronesia', 'country', NULL),
  ('Moldova', 'country', NULL),
  ('Monaco', 'country', NULL),
  ('Mongolia', 'country', NULL),
  ('Montenegro', 'country', NULL),
  ('Morocco', 'country', NULL),
  ('Mozambique', 'country', NULL),
  ('Myanmar', 'country', NULL),
  ('Namibia', 'country', NULL),
  ('Nauru', 'country', NULL),
  ('Nepal', 'country', NULL),
  ('Netherlands', 'country', NULL),
  ('New Zealand', 'country', NULL),
  ('Nicaragua', 'country', NULL),
  ('Niger', 'country', NULL),
  ('Nigeria', 'country', NULL),
  ('North Korea', 'country', NULL),
  ('North Macedonia', 'country', NULL),
  ('Norway', 'country', NULL),
  ('Oman', 'country', NULL),
  ('Pakistan', 'country', NULL),
  ('Palau', 'country', NULL),
  ('Palestine', 'country', NULL),
  ('Panama', 'country', NULL),
  ('Papua New Guinea', 'country', NULL),
  ('Paraguay', 'country', NULL),
  ('Peru', 'country', NULL),
  ('Philippines', 'country', NULL),
  ('Poland', 'country', NULL),
  ('Portugal', 'country', NULL),
  ('Qatar', 'country', NULL),
  ('Romania', 'country', NULL),
  ('Russia', 'country', NULL),
  ('Rwanda', 'country', NULL),
  ('Saint Kitts and Nevis', 'country', NULL),
  ('Saint Lucia', 'country', NULL),
  ('Saint Vincent and the Grenadines', 'country', NULL),
  ('Samoa', 'country', NULL),
  ('San Marino', 'country', NULL),
  ('Sao Tome and Principe', 'country', NULL),
  ('Saudi Arabia', 'country', NULL),
  ('Senegal', 'country', NULL),
  ('Serbia', 'country', NULL),
  ('Seychelles', 'country', NULL),
  ('Sierra Leone', 'country', NULL),
  ('Singapore', 'country', NULL),
  ('Slovakia', 'country', NULL),
  ('Slovenia', 'country', NULL),
  ('Solomon Islands', 'country', NULL),
  ('Somalia', 'country', NULL),
  ('South Africa', 'country', NULL),
  ('South Korea', 'country', NULL),
  ('South Sudan', 'country', NULL),
  ('Spain', 'country', NULL),
  ('Sri Lanka', 'country', NULL),
  ('Sudan', 'country', NULL),
  ('Suriname', 'country', NULL),
  ('Sweden', 'country', NULL),
  ('Switzerland', 'country', NULL),
  ('Syria', 'country', NULL),
  ('Taiwan', 'country', NULL),
  ('Tajikistan', 'country', NULL),
  ('Tanzania', 'country', NULL),
  ('Thailand', 'country', NULL),
  ('Timor-Leste', 'country', NULL),
  ('Togo', 'country', NULL),
  ('Tonga', 'country', NULL),
  ('Trinidad and Tobago', 'country', NULL),
  ('Tunisia', 'country', NULL),
  ('Turkey', 'country', NULL),
  ('Turkmenistan', 'country', NULL),
  ('Tuvalu', 'country', NULL),
  ('Uganda', 'country', NULL),
  ('Ukraine', 'country', NULL),
  ('United Arab Emirates', 'country', NULL),
  ('United Kingdom', 'country', NULL),
  ('United States', 'country', NULL),
  ('Uruguay', 'country', NULL),
  ('Uzbekistan', 'country', NULL),
  ('Vanuatu', 'country', NULL),
  ('Vatican City', 'country', NULL),
  ('Venezuela', 'country', NULL),
  ('Vietnam', 'country', NULL),
  ('Yemen', 'country', NULL),
  ('Zambia', 'country', NULL),
  ('Zimbabwe', 'country', NULL)
ON CONFLICT (name, parent_id) DO NOTHING;
