-- Seed common minerals
-- This provides a starting list that users can reference when adding specimens

INSERT INTO public.minerals (name) VALUES
  -- Silicates
  ('Quartz'),
  ('Amethyst'),
  ('Citrine'),
  ('Rose Quartz'),
  ('Smoky Quartz'),
  ('Chalcedony'),
  ('Agate'),
  ('Jasper'),
  ('Opal'),
  ('Feldspar'),
  ('Orthoclase'),
  ('Microcline'),
  ('Amazonite'),
  ('Labradorite'),
  ('Moonstone'),
  ('Sunstone'),
  ('Albite'),
  ('Oligoclase'),
  ('Andesine'),
  ('Mica'),
  ('Muscovite'),
  ('Biotite'),
  ('Lepidolite'),
  ('Phlogopite'),
  ('Pyroxene'),
  ('Augite'),
  ('Diopside'),
  ('Enstatite'),
  ('Hypersthene'),
  ('Spodumene'),
  ('Kunzite'),
  ('Hiddenite'),
  ('Amphibole'),
  ('Hornblende'),
  ('Tremolite'),
  ('Actinolite'),
  ('Nephrite'),
  ('Olivine'),
  ('Peridot'),
  ('Forsterite'),
  ('Fayalite'),
  ('Garnet'),
  ('Almandine'),
  ('Pyrope'),
  ('Spessartine'),
  ('Grossular'),
  ('Andradite'),
  ('Uvarovite'),
  ('Tourmaline'),
  ('Schorl'),
  ('Elbaite'),
  ('Rubellite'),
  ('Indicolite'),
  ('Watermelon Tourmaline'),
  ('Beryl'),
  ('Emerald'),
  ('Aquamarine'),
  ('Morganite'),
  ('Heliodor'),
  ('Goshenite'),
  ('Topaz'),
  ('Zircon'),
  ('Titanite'),
  ('Sphene'),
  ('Epidote'),
  ('Zoisite'),
  ('Tanzanite'),
  ('Prehnite'),
  ('Kyanite'),
  ('Sillimanite'),
  ('Andalusite'),
  ('Staurolite'),
  ('Chlorite'),
  ('Serpentine'),
  ('Chrysotile'),
  ('Antigorite'),
  ('Talc'),
  ('Sodalite'),
  ('Lazurite'),
  ('Lapis Lazuli'),
  ('Hauyne'),
  ('Rhodonite'),
  ('Wollastonite'),
  ('Pectolite'),
  ('Larimar'),
  ('Chrysocolla'),
  ('Hemimorphite'),
  ('Smithsonite'),
  ('Willemite'),

  -- Carbonates
  ('Calcite'),
  ('Aragonite'),
  ('Dolomite'),
  ('Magnesite'),
  ('Siderite'),
  ('Rhodochrosite'),
  ('Malachite'),
  ('Azurite'),
  ('Cerussite'),
  ('Witherite'),
  ('Strontianite'),

  -- Sulfates
  ('Gypsum'),
  ('Selenite'),
  ('Alabaster'),
  ('Anhydrite'),
  ('Barite'),
  ('Celestine'),
  ('Anglesite'),
  ('Jarosite'),

  -- Sulfides
  ('Pyrite'),
  ('Marcasite'),
  ('Chalcopyrite'),
  ('Bornite'),
  ('Covellite'),
  ('Chalcocite'),
  ('Galena'),
  ('Sphalerite'),
  ('Cinnabar'),
  ('Realgar'),
  ('Orpiment'),
  ('Stibnite'),
  ('Molybdenite'),
  ('Arsenopyrite'),
  ('Pyrrhotite'),
  ('Pentlandite'),
  ('Millerite'),
  ('Acanthite'),
  ('Argentite'),
  ('Proustite'),
  ('Pyrargyrite'),

  -- Oxides
  ('Hematite'),
  ('Magnetite'),
  ('Ilmenite'),
  ('Chromite'),
  ('Spinel'),
  ('Corundum'),
  ('Ruby'),
  ('Sapphire'),
  ('Rutile'),
  ('Cassiterite'),
  ('Uraninite'),
  ('Cuprite'),
  ('Goethite'),
  ('Limonite'),
  ('Pyrolusite'),
  ('Manganite'),
  ('Psilomelane'),
  ('Columbite'),
  ('Tantalite'),
  ('Chrysoberyl'),
  ('Alexandrite'),

  -- Halides
  ('Halite'),
  ('Sylvite'),
  ('Fluorite'),
  ('Cryolite'),
  ('Carnallite'),

  -- Phosphates
  ('Apatite'),
  ('Turquoise'),
  ('Variscite'),
  ('Vivianite'),
  ('Wavellite'),
  ('Pyromorphite'),
  ('Vanadinite'),
  ('Autunite'),
  ('Torbernite'),
  ('Monazite'),
  ('Xenotime'),
  ('Lazulite'),
  ('Amblygonite'),
  ('Brazilianite'),

  -- Native Elements
  ('Native Gold'),
  ('Native Silver'),
  ('Native Copper'),
  ('Native Platinum'),
  ('Native Iron'),
  ('Diamond'),
  ('Graphite'),
  ('Sulfur'),

  -- Tungstates and Molybdates
  ('Scheelite'),
  ('Wolframite'),
  ('Wulfenite'),
  ('Powellite'),

  -- Borates
  ('Borax'),
  ('Ulexite'),
  ('Colemanite'),
  ('Kernite'),

  -- Other Notable Minerals
  ('Jet'),
  ('Amber'),
  ('Pearl'),
  ('Coral'),
  ('Obsidian'),
  ('Moldavite'),
  ('Tektite'),
  ('Fulgurite'),
  ('Shungite'),
  ('Charoite'),
  ('Sugilite'),
  ('Eudialyte'),
  ('Danburite'),
  ('Phenakite'),
  ('Dioptase'),
  ('Benitoite'),
  ('Seraphinite'),
  ('Pietersite'),
  ('Dumortierite'),
  ('Iolite'),
  ('Cordierite')
ON CONFLICT (name) DO NOTHING;
